### ISSUE TITLE
Extend register and token predicates parameter to receive not one but all values 

### ISSUE THREAD

**Issue by greenhat** [robkorn/ergo-utilities-rust#1]
## Motivation
1. To be able to check the properties of a particular register/token (e.g. only R6). 
2. Avoid the burden of keeping/enforcing the mapping of predicates to registers/tokens.

## Possible implementation
Rename structs and change signatures:
```
pub struct RegistersPredicate {
    predicate: fn(&NonMandatoryRegisters) -> bool,
}

pub struct TokensPredicate {
    predicate: fn(&Vec<TokenAmount>) -> bool,
}

```

**Comment by robkorn** [comment]
Ah interesting. So the idea is to effectively outsource the structure of the registers/tokens to the predicate rather than keep the mapping.

Good idea. Now that I think about it, a further benefit to this approach is that it enables cross-register/cross-token checks. Originally each predicate had no context available to it about other registers or tokens.
